from typing import Annotated, Optional
from typing_extensions import TypedDict
from langgraph.graph import MessagesState


# Researcher team state
class InvestDebateState(TypedDict):
    bull_history: Annotated[
        str, "Bullish Conversation history"
    ]  # Bullish Conversation history
    bear_history: Annotated[
        str, "Bearish Conversation history"
    ]  # Bullish Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    current_response: Annotated[str, "Latest response"]  # Last response
    judge_decision: Annotated[str, "Final judge decision"]  # Last response
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


# Risk management team state
class RiskDebateState(TypedDict):
    aggressive_history: Annotated[
        str, "Aggressive Agent's Conversation history"
    ]  # Conversation history
    conservative_history: Annotated[
        str, "Conservative Agent's Conversation history"
    ]  # Conversation history
    neutral_history: Annotated[
        str, "Neutral Agent's Conversation history"
    ]  # Conversation history
    history: Annotated[str, "Conversation history"]  # Conversation history
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_aggressive_response: Annotated[
        str, "Latest response by the aggressive analyst"
    ]  # Last response
    current_conservative_response: Annotated[
        str, "Latest response by the conservative analyst"
    ]  # Last response
    current_neutral_response: Annotated[
        str, "Latest response by the neutral analyst"
    ]  # Last response
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]  # Conversation length


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]

    sender: Annotated[str, "Agent that sent this message"]

    # research step
    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]
    policy_report: Annotated[str, "Report from the Policy Analyst (A-stock specific)"]
    hot_money_report: Annotated[str, "Report from the Hot Money Tracker (A-stock specific)"]
    lockup_report: Annotated[str, "Report from the Lockup/Reduction Watcher (A-stock specific)"]

    # data quality gate
    data_quality_summary: Annotated[str, "Quality gate assessment of all analyst reports (hard checks + LLM review)"]

    # researcher team discussion step
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # risk management team discussion step
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
    risk_control_decision: Annotated[str, "Risk control decision from the risk manager"]
    past_context: Annotated[str, "Memory log context injected at run start (same-ticker decisions + cross-ticker lessons)"]

    # accuracy guardian (quality assurance)
    _accuracy_guardian_report: Annotated[dict, "Full accuracy guardian report object"]
    _quality_grade: Annotated[str, "Overall quality grade (A/B/C/D/F)"]
    _confidence_level: Annotated[str, "Confidence level (高/中/低/谨慎参考/不可靠)"]
    _overall_quality_score: Annotated[float, "Overall quality score (0-1)"]
    _should_trust: Annotated[bool, "Whether the conclusion should be trusted"]
    _trust_reason: Annotated[str, "Reason for trust/distrust"]

    # debate convergence reports
    _debate_reports: Annotated[dict, "Debate convergence reports (investment + risk)"]

    # data integrity reports
    _integrity_reports: Annotated[dict, "Data integrity reports from batch integrity manager"]

    # formula-based hard scoring (rework 2)
    _formula_scores: Annotated[dict, "Formula-based hard scores per analyst {analyst_type: {score, available, source}}"]
    _analyst_tool_data: Annotated[dict, "Raw tool outputs per analyst {analyst_type: {tool_name: [str]}}"]

    # structured decision objects (dual-write, rework 3)
    # 生产端节点同时产出渲染字符串（investment_plan 等）与结构化对象（model_dump dict），
    # 消费端优先读对象、空则回退字符串正则解析，避免多处重复解析同一信息。
    research_plan_object: Annotated[Optional[dict], "ResearchPlan.model_dump()"]
    trader_plan_object: Annotated[Optional[dict], "TraderProposal.model_dump()"]
    risk_control_object: Annotated[Optional[dict], "RiskControlDecision.model_dump()"]
    final_decision_object: Annotated[Optional[dict], "PortfolioDecision.model_dump()"]
    final_rating: Annotated[Optional[str], "Normalized rating: 买入/增持/持有/减持/卖出"]
    final_confidence: Annotated[Optional[float], "Normalized confidence 0-1 (conviction/100)"]
    max_position_size: Annotated[Optional[float], "Risk control max position (%)"]
    recommended_position_size: Annotated[Optional[float], "Risk control recommended position (%)"]
